feat: allow to define alerts for a consumer
gravitee-io/gravitee-portal-webui pull request #396
Opened 2021-05-18 07:35 UTC by ytvnr

Fixes https://github.com/gravitee-io/issues/issues/5341

2021-05-24 12:35 UTC, phiz71 requested changes
This file should not be generated and commited `projects/portal-webclient-sdk/src/lib/model/alertsResponse.ts`

Clean your `projects` lib and regenerate the files

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.css
> +.form gv-select,
use a class name dedicated to this component. For example .gv-alert__form, .gv-alert__row, etc... To avoid conflict with other CSS files.

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.ts
> +      this.timeUnits = ['S', 'MINUTES', 'HOURS'];
useless ? (see line 149)

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.ts
> +              value: 'HOURS',
Why not using the enum generated from the openAPI descriptor ?
See `projects/portal-webclient-sdk/src/lib/model/alertTimeUnit.ts`

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.ts
> +              value: 'MINUTES',
Why not using the enum generated from the openAPI descriptor ?
See `projects/portal-webclient-sdk/src/lib/model/alertTimeUnit.ts`

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.ts
> +              value: 'SECONDS',
Why not using the enum generated from the openAPI descriptor ?
See `projects/portal-webclient-sdk/src/lib/model/alertTimeUnit.ts`

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.ts
> +              value: 'RESPONSE_TIME',
Why not using the enum generated from the openAPI descriptor ?
See `projects/portal-webclient-sdk/src/lib/model/alertType.ts`

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.ts
> +              value: 'STATUS',
Why not using the enum generated from the openAPI descriptor ?
See `projects/portal-webclient-sdk/src/lib/model/alertType.ts`

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.ts
> +    if ($event === 'STATUS') {
Why not using the enum generated from the openAPI descriptor ?
See `projects/portal-webclient-sdk/src/lib/model/alertType.ts`

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-alert/gv-alert.component.ts
> +      timeUnit: new FormControl('MINUTES', [Validators.required]),
Why not using the enum generated from the openAPI descriptor ?
See `projects/portal-webclient-sdk/src/lib/model/alertTimeUnit.ts`
and `projects/portal-webclient-sdk/src/lib/model/alertType.ts`

2021-05-24 12:35 UTC, phiz71 commented on src/app/components/gv-analytics-dashboard/gv-analytics-dashboard.component.ts
> +    return title === 'Response times' || title === 'Response Status';
Response Status => HTTP Status ?

2021-05-24 12:35 UTC, phiz71 commented on src/app/pages/application/application-alerts/application-alerts.component.css
> +.page__box-information {
Maybe you should add a specific CSS class, shouldn't you ?

2021-05-24 12:45 UTC, ytvnr commented on src/app/components/gv-analytics-dashboard/gv-analytics-dashboard.component.ts
> +    return title === 'Response times' || title === 'Response Status';
![image](https://user-images.githubusercontent.com/47851994/119349576-97a59d00-bc9e-11eb-89f4-75c73be416e7.png)

2021-05-25 07:17 UTC, phiz71 commented on src/app/components/gv-analytics-dashboard/gv-analytics-dashboard.component.ts
> +    return title === 'Response times' || title === 'Response Status';
ok

2021-05-25 07:34 UTC, merged